package com.api.paideia.controllers;

import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import com.api.paideia.domain.chatbot.Answer;
import com.api.paideia.domain.chatbot.Question;
import com.api.paideia.repositories.chatbot.AnswerRepository;
import com.api.paideia.repositories.chatbot.QuestionRepository;

@Component
public class DataInitializer implements CommandLineRunner {
    private final QuestionRepository questionRepository;
    private final AnswerRepository answerRepository;

    // Lista de perguntas e respostas personalizadas
    private final List<String> questions = List.of(
            "Oi",
            "Olá",
            "Oi, tudo bem?",
            "Olá, tudo bem?",
            "Tudo bem?",
            "Você tá bem?",
            "Como vai?",
            "Pode me ajudar?",
            "Poderia me ajudar?",
            "Tenho uma dúvida",
            "Quem é vc?",
            "Quem é você?",
            "Como é seu nome?",
            "Como você se chama?",
            "Você tem nome?",
            "Obrigado",
            "Muito obrigado",
            "Tchau",
            "O que é Paideia?",
            "O que significa Paideia?",
            "De onde vem o nome Paideia?",
            "O que significa a palavra Paideia?",
            "O que significa o nome Paideia?",
            "O que é o sistema Paideia?",
            "O que é a plataforma Paideia?",
            "Para que serve o Paideia?",
            "Para que serve esse sistema?",
            "Para que serve este sistema?",
            "Para que serve essa plataforma?",
            "Para que serve esta plataforma?",
            "Quem é o público-alvo?",
            "Qual é o público-alvo?",
            "A quem se destina o Paideia?",
            "A quem se destina esse site?",
            "A quem se destina este site?",
            "A quem se destina essa plataforma?",
            "A quem se destina esta plataforma?",
            "Quem pode usar o Paideia?",
            "Quem pode usar esse site?",
            "Quem pode usar este site?",
            "Quem pode usar essa plataforma?",
            "Quem pode usar esta plataforma?",
            "Sou estudante. Posso usar o Paideia?",
            "Sou pesquisador. Posso usar o Paideia?",
            "Não sou estudante. Posso usar o Paideia?",
            "Sou professor. Posso usar o Paideia?",
            "Sou autodidata. Posso usar o Paideia?",
            "Qual é a finalidade do Paideia?",
            "O que este site faz?",
            "O que esse site faz?",
            "O que essa plataforma faz?",
            "O que esta plataforma faz?",
            "O que posso fazer no Paideia?",
            "O que posso fazer neste site?",
            "O que posso fazer nesse site?",
            "O que posso fazer nesta plataforma?",
            "O que posso fazer nessa plataforma?",
            "O que faço no Paideia?",
            "O que faço neste site?",
            "O que faço nesse site?",
            "O que faço nesta plataforma?",
            "O que faço nessa plataforma?",
            "Posso cadastrar cursos no Paideia?",
            "Posso cadastrar meus cursos no Paideia?",
            "Posso adicionar cursos no Paideia?",
            "Posso adicionar meus cursos no Paideia?",
            "Posso cadastrar cursos?",
            "Posso cadastrar meus cursos?",
            "Posso adicionar cursos?",
            "Posso adicionar meus cursos?",
            "Como faço para adicionar um curso?",
            "Como faço para cadastrar um curso?",
            "Como adiciono um curso?",
            "Como cadastro um curso?",
            "Como adiciono meus cursos?",
            "Como cadastro meus cursos?",
            "O que acontece após cadastrar um curso?",
            "O que acontece após adicionar um curso?",
            "O que posso fazer após cadastrar um curso?",
            "O que posso fazer após adicionar um curso?",
            "O que faço após cadastrar meus cursos?",
            "O que faço após adicionar meus cursos?",
            "Posso cadastrar disciplinas no Paideia?",
            "Posso cadastrar minhas disciplinas no Paideia?",
            "Posso adicionar disciplinas no Paideia?",
            "Posso adicionar minhas disciplinas no Paideia?",
            "Posso cadastrar disciplinas?",
            "Posso cadastrar minhas disciplinas?",
            "Posso adicionar disciplinas?",
            "Posso adicionar minhas disciplinas?",
            "Como faço para adicionar uma disciplina?",
            "Como faço para cadastrar uma disciplina?",
            "Como adiciono uma disciplina?",
            "Como cadastro uma disciplina?",
            "Como adiciono minhas disciplinas?",
            "Como cadastro minhas disciplinas?",
            "O que acontece após cadastrar uma disciplina?",
            "O que acontece após adicionar uma disciplina?",
            "O que posso fazer após cadastrar uma disciplina?",
            "O que posso fazer após adicionar uma disciplina?",
            "O que faço após cadastrar minhas disciplinas?",
            "O que faço após adicionar minhas disciplinas?",
            "Posso cadastrar pesquisas no Paideia?",
            "Posso cadastrar minhas pesquisas no Paideia?",
            "Posso adicionar pesquisas no Paideia?",
            "Posso adicionar minhas pesquisas no Paideia?",
            "Posso cadastrar pesquisas?",
            "Posso cadastrar minhas pesquisas?",
            "Posso adicionar pesquisas?",
            "Posso adicionar minhas pesquisas?",
            "Como faço para adicionar uma pesquisa?",
            "Como faço para cadastrar uma pesquisa?",
            "Como adiciono uma pesquisa?",
            "Como cadastro uma pesquisa?",
            "Como adiciono minhas pesquisas?",
            "Como cadastro minhas pesquisas?",
            "O que acontece após cadastrar uma pesquisa?",
            "O que acontece após adicionar uma pesquisa?",
            "O que posso fazer após cadastrar uma pesquisa?",
            "O que posso fazer após adicionar uma pesquisa?",
            "O que faço após cadastrar minhas pesquisas?",
            "O que faço após adicionar minhas pesquisas?",
            "Posso cadastrar referências no Paideia?",
            "Posso cadastrar minhas referências no Paideia?",
            "Posso adicionar referências no Paideia?",
            "Posso adicionar minhas referências no Paideia?",
            "Posso cadastrar referências?",
            "Posso cadastrar minhas referências?",
            "Posso adicionar referências?",
            "Posso adicionar minhas referências?",
            "Como faço para adicionar uma referência?",
            "Como faço para cadastrar uma referência?",
            "Como adiciono uma referência?",
            "Como cadastro uma referência?",
            "Como adiciono minhas referências?",
            "Como cadastro minhas referências?",
            "O que acontece após cadastrar uma referência?",
            "O que acontece após adicionar uma referência?",
            "O que posso fazer após cadastrar uma referência?",
            "O que posso fazer após adicionar uma referência?",
            "O que faço após cadastrar minhas referências?",
            "O que faço após adicionar minhas referências?",
            "Como funciona a atribuição de referências?",
            "O que é atribuição de referências?",
            "Para que serve a atribuição de referências?",
            "O que é um curso?",
            "O que é uma disciplina?",
            "O que é uma pesquisa acadêmica?",
            "O que é uma referência?");

    private final List<String> answers = List.of(
            "Olá! Como vai? Sou a coruja Minerva, o chatbot do Paideia 🦉. Como posso ajudar? Você pode fazer uma pergunta ou digitar SAIR para encerrar o chat",
            "Olá! Como vai? Sou a coruja Minerva, o chatbot do Paideia 🦉. Como posso ajudar? Você pode fazer uma pergunta ou digitar SAIR para encerrar o chat",
            "Olá! Eu vou bem, e você? Sou a coruja Minerva, o chatbot do Paideia 🦉. Você pode fazer uma pergunta ou digitar SAIR para encerrar o chat",
            "Olá! Eu vou bem, e você? Sou a coruja Minerva, o chatbot do Paideia 🦉. Você pode fazer uma pergunta ou digitar SAIR para encerrar o chat",
            "Tudo ótimo, e você? Em que posso ajudá-lo?",
            "Tudo ótimo, e você? Em que posso ajudá-lo?",
            "Tudo ótimo, e você? Em que posso ajudá-lo?",
            "Claro! Em que posso ajudar você?",
            "Claro! Em que posso ajudar você?",
            "Pode perguntar, estou aqui para ajudá-lo!",
            "Sou a coruja Minerva, o chatbot do Paideia 🦉. Estou aqui para auxiliá-lo com suas dúvidas",
            "Sou a coruja Minerva, o chatbot do Paideia 🦉. Estou aqui para auxiliá-lo com suas dúvidas",
            "Sou a coruja Minerva, o chatbot do Paideia 🦉. Estou aqui para auxiliá-lo com suas dúvidas",
            "Sou a coruja Minerva, o chatbot do Paideia 🦉. Estou aqui para auxiliá-lo com suas dúvidas",
            "Sou a coruja Minerva, o chatbot do Paideia 🦉. Estou aqui para auxiliá-lo com suas dúvidas",
            "Disponha! Estou aqui para ajudá-lo!",
            "Disponha! Estou aqui para ajudá-lo!",
            "Até logo! Venha me procurar caso tenha mais dúvidas!",
            "Paideia era o nome dado ao conceito de educação formal e formação ética, cultural e social na Grécia Antiga 📚",
            "Paideia era o nome dado ao conceito de educação formal e formação ética, cultural e social na Grécia Antiga 📚",
            "Paideia era o nome dado ao conceito de educação formal e formação ética, cultural e social na Grécia Antiga 📚",
            "Paideia era o nome dado ao conceito de educação formal e formação ética, cultural e social na Grécia Antiga 📚",
            "Paideia era o nome dado ao conceito de educação formal e formação ética, cultural e social na Grécia Antiga 📚",
            "O Paideia é um sistema de gerenciamento de referências e organização de estudos",
            "O Paideia é um sistema de gerenciamento de referências e organização de estudos",
            "O Paideia é um sistema de gerenciamento de referências e organização de estudos",
            "O Paideia é um sistema de gerenciamento de referências e organização de estudos",
            "O Paideia é um sistema de gerenciamento de referências e organização de estudos",
            "O Paideia é um sistema de gerenciamento de referências e organização de estudos",
            "O Paideia é um sistema de gerenciamento de referências e organização de estudos",
            "Estudantes e/ou pesquisadores que estão matriculados em algum programa de ensino",
            "Estudantes e/ou pesquisadores que estão matriculados em algum programa de ensino",
            "Estudantes e/ou pesquisadores que estão matriculados em algum programa de ensino",
            "Estudantes e/ou pesquisadores que estão matriculados em algum programa de ensino",
            "Estudantes e/ou pesquisadores que estão matriculados em algum programa de ensino",
            "Estudantes e/ou pesquisadores que estão matriculados em algum programa de ensino",
            "Estudantes e/ou pesquisadores que estão matriculados em algum programa de ensino",
            "Atualmente, nossas funcionalidades são direcionadas a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "Atualmente, nossas funcionalidades são direcionadas a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "Atualmente, nossas funcionalidades são direcionadas a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "Atualmente, nossas funcionalidades são direcionadas a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "Atualmente, nossas funcionalidades são direcionadas a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "Sim! Atualmente, nossas funcionalidades são direcionadas a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "Sim! Atualmente, nossas funcionalidades são direcionadas a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "No momento, nossas funcionalidades são direcionadas, sobretudo, a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "No momento, nossas funcionalidades são direcionadas, sobretudo, a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "No momento, nossas funcionalidades são direcionadas, sobretudo, a estudantes e/ou pesquisadores matriculados em algum programa de ensino",
            "É uma plataforma para estudantes e/ou pesquisadores organizarem seus estudos",
            "É uma plataforma para estudantes e/ou pesquisadores organizarem seus estudos",
            "É uma plataforma para estudantes e/ou pesquisadores organizarem seus estudos",
            "É uma plataforma para estudantes e/ou pesquisadores organizarem seus estudos",
            "É uma plataforma para estudantes e/ou pesquisadores organizarem seus estudos",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Você pode cadastrar seus Cursos. Dentro de cada Curso, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas. Após cadastrar Disciplinas ou Pesquisas, é possível adicionar Referências e atribui-las às Disciplinas ou Pesquisas",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Sim, você pode cadastrar seus Cursos no Paideia. Basta acessar a aba Cursos, no menu lateral, e clicar no + para adicionar um Curso",
            "Para cadastrar seus Cursos no Paideia, acesse a aba Cursos, através do menu lateral, e clique no botão +",
            "Para cadastrar seus Cursos no Paideia, acesse a aba Cursos, através do menu lateral, e clique no botão +",
            "Para cadastrar seus Cursos no Paideia, acesse a aba Cursos, através do menu lateral, e clique no botão +",
            "Para cadastrar seus Cursos no Paideia, acesse a aba Cursos, através do menu lateral, e clique no botão +",
            "Para cadastrar seus Cursos no Paideia, acesse a aba Cursos, através do menu lateral, e clique no botão +",
            "Para cadastrar seus Cursos no Paideia, acesse a aba Cursos, através do menu lateral, e clique no botão +",
            "Após cadastrar um Curso, o sistema cria uma página de Curso. Você pode acessar a página do Curso cadastrado através da tela inicial ou do menu lateral, na aba Cursos. Tendo um Curso cadastrado no sistema, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas a esse Curso, através da página do Curso",
            "Após cadastrar um Curso, o sistema cria uma página de Curso. Você pode acessar a página do Curso cadastrado através da tela inicial ou do menu lateral, na aba Cursos. Tendo um Curso cadastrado no sistema, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas a esse Curso, através da página do Curso",
            "Após cadastrar um Curso, o sistema cria uma página de Curso. Você pode acessar a página do Curso cadastrado através da tela inicial ou do menu lateral, na aba Cursos. Tendo um Curso cadastrado no sistema, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas a esse Curso, através da página do Curso",
            "Após cadastrar um Curso, o sistema cria uma página de Curso. Você pode acessar a página do Curso cadastrado através da tela inicial ou do menu lateral, na aba Cursos. Tendo um Curso cadastrado no sistema, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas a esse Curso, através da página do Curso",
            "Após cadastrar um Curso, o sistema cria uma página de Curso. Você pode acessar a página do Curso cadastrado através da tela inicial ou do menu lateral, na aba Cursos. Tendo um Curso cadastrado no sistema, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas a esse Curso, através da página do Curso",
            "Após cadastrar um Curso, o sistema cria uma página de Curso. Você pode acessar a página do Curso cadastrado através da tela inicial ou do menu lateral, na aba Cursos. Tendo um Curso cadastrado no sistema, você pode adicionar Disciplinas e/ou Pesquisas Acadêmicas a esse Curso, através da página do Curso",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Disciplinas no Paideia. Para adicionar uma Disciplina, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Para cadastrar suas Disciplinas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Disciplinas",
            "Para cadastrar suas Disciplinas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Disciplinas",
            "Para cadastrar suas Disciplinas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Disciplinas",
            "Para cadastrar suas Disciplinas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Disciplinas",
            "Para cadastrar suas Disciplinas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Disciplinas",
            "Para cadastrar suas Disciplinas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Disciplinas",
            "Após cadastrar uma Disciplina, o sistema cria uma página de Disciplina. Você pode acessar a página da Disciplina através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Disciplina, o sistema cria uma página de Disciplina. Você pode acessar a página da Disciplina através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Disciplina, o sistema cria uma página de Disciplina. Você pode acessar a página da Disciplina através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Disciplina, o sistema cria uma página de Disciplina. Você pode acessar a página da Disciplina através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Disciplina, o sistema cria uma página de Disciplina. Você pode acessar a página da Disciplina através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Disciplina, o sistema cria uma página de Disciplina. Você pode acessar a página da Disciplina através da página do Curso no qual ela foi cadastrada",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Sim, você pode cadastrar suas Pesquisas Acadêmicas no Paideia. Para adicionar uma Pesquisa, é necessário ter um Curso cadastrado. Basta acessar a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral",
            "Para cadastrar suas Pesquisas Acadêmicas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Pesquisas",
            "Para cadastrar suas Pesquisas Acadêmicas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Pesquisas",
            "Para cadastrar suas Pesquisas Acadêmicas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Pesquisas",
            "Para cadastrar suas Pesquisas Acadêmicas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Pesquisas",
            "Para cadastrar suas Pesquisas Acadêmicas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Pesquisas",
            "Para cadastrar suas Pesquisas Acadêmicas no Paideia, é necessário ter um Curso cadastrado. Acesse a página do Curso, através da tela inicial ou da aba Cursos, no menu lateral, e clique no botão + sob a seção Pesquisas",
            "Após cadastrar uma Pesquisa Acadêmica, o sistema cria uma página de Pesquisa Acadêmica. Você pode acessar a página da Pesquisa através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Pesquisa Acadêmica, o sistema cria uma página de Pesquisa Acadêmica. Você pode acessar a página da Pesquisa através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Pesquisa Acadêmica, o sistema cria uma página de Pesquisa Acadêmica. Você pode acessar a página da Pesquisa através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Pesquisa Acadêmica, o sistema cria uma página de Pesquisa Acadêmica. Você pode acessar a página da Pesquisa através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Pesquisa Acadêmica, o sistema cria uma página de Pesquisa Acadêmica. Você pode acessar a página da Pesquisa através da página do Curso no qual ela foi cadastrada",
            "Após cadastrar uma Pesquisa Acadêmica, o sistema cria uma página de Pesquisa Acadêmica. Você pode acessar a página da Pesquisa através da página do Curso no qual ela foi cadastrada",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Sim, você pode cadastrar suas Referências no Paideia. Para adicionar uma Referência, é necessário ter Disciplinas ou Pesquisas cadastradas",
            "Para cadastrar suas Referências no Paideia, é necessário ter Disciplinas ou Pesquisas cadastradas. Acesse a aba Referências, através do menu lateral, e clique no botão Adicionar Referência",
            "Para cadastrar suas Referências no Paideia, é necessário ter Disciplinas ou Pesquisas cadastradas. Acesse a aba Referências, através do menu lateral, e clique no botão Adicionar Referência",
            "Para cadastrar suas Referências no Paideia, é necessário ter Disciplinas ou Pesquisas cadastradas. Acesse a aba Referências, através do menu lateral, e clique no botão Adicionar Referência",
            "Para cadastrar suas Referências no Paideia, é necessário ter Disciplinas ou Pesquisas cadastradas. Acesse a aba Referências, através do menu lateral, e clique no botão Adicionar Referência",
            "Para cadastrar suas Referências no Paideia, é necessário ter Disciplinas ou Pesquisas cadastradas. Acesse a aba Referências, através do menu lateral, e clique no botão Adicionar Referência",
            "Para cadastrar suas Referências no Paideia, é necessário ter Disciplinas ou Pesquisas cadastradas. Acesse a aba Referências, através do menu lateral, e clique no botão Adicionar Referência",
            "Após cadastrar uma Referência, o sistema adiciona a Referência a uma lista de Referências, e a Referência é atribuída à Disciplina e/ou Pesquisa escolhida. Você pode visualizar a Referência na aba de Referências ou na página da Disciplina/Pesquisa à qual a Referência foi atribuída",
            "Após cadastrar uma Referência, o sistema adiciona a Referência a uma lista de Referências, e a Referência é atribuída à Disciplina e/ou Pesquisa escolhida. Você pode visualizar a Referência na aba de Referências ou na página da Disciplina/Pesquisa à qual a Referência foi atribuída",
            "Após cadastrar uma Referência, o sistema adiciona a Referência a uma lista de Referências, e a Referência é atribuída à Disciplina e/ou Pesquisa escolhida. Você pode visualizar a Referência na aba de Referências ou na página da Disciplina/Pesquisa à qual a Referência foi atribuída",
            "Após cadastrar uma Referência, o sistema adiciona a Referência a uma lista de Referências, e a Referência é atribuída à Disciplina e/ou Pesquisa escolhida. Você pode visualizar a Referência na aba de Referências ou na página da Disciplina/Pesquisa à qual a Referência foi atribuída",
            "Após cadastrar uma Referência, o sistema adiciona a Referência a uma lista de Referências, e a Referência é atribuída à Disciplina e/ou Pesquisa escolhida. Você pode visualizar a Referência na aba de Referências ou na página da Disciplina/Pesquisa à qual a Referência foi atribuída",
            "Após cadastrar uma Referência, o sistema adiciona a Referência a uma lista de Referências, e a Referência é atribuída à Disciplina e/ou Pesquisa escolhida. Você pode visualizar a Referência na aba de Referências ou na página da Disciplina/Pesquisa à qual a Referência foi atribuída",
            "A atribuição de Referências serve para atribuir uma Referência a uma Disciplina e/ou Pesquisa cadastradas dentro de um Curso. Dessa forma, o estudante pode manter organizadas as Referências utilizadas naquela Disciplina ou Pesquisa",
            "A atribuição de Referências serve para atribuir uma Referência a uma Disciplina e/ou Pesquisa cadastradas dentro de um Curso. Dessa forma, o estudante pode manter organizadas as Referências utilizadas naquela Disciplina ou Pesquisa",
            "A atribuição de Referências serve para atribuir uma Referência a uma Disciplina e/ou Pesquisa cadastradas dentro de um Curso. Dessa forma, o estudante pode manter organizadas as Referências utilizadas naquela Disciplina ou Pesquisa",
            "No Paideia, um Curso representa um conjunto de aulas e/ou atividades organizadas em um programa de estudos que oferece uma formação, titulação e/ou certificação",
            "No Paideia, uma Disciplina representa uma subdivisão do currículo de um curso em unidades menores focadas em conhecimentos específicos e direcionados",
            "No Paideia, uma Pesquisa Acadêmica representa um trabalho de investigação de determinado assunto para ampliar o conhecimento acerca do tema",
            "No Paideia, uma Referência representa uma fonte de informação e/ou uma produção científica/criativa utilizada na realização de trabalhos e/ou pesquisas acadêmicas");

    public DataInitializer(QuestionRepository questionRepository, AnswerRepository answerRepository) {
        this.questionRepository = questionRepository;
        this.answerRepository = answerRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        for (int i = 0; i < questions.size(); i++) {
            Question question = new Question();
            question.setContent(questions.get(i));
            questionRepository.save(question);

            Answer answer = new Answer();
            answer.setContent(answers.get(i));
            answer.setQuestion(question);
            answerRepository.save(answer);
        }
    }

}